#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Commit test init...'

# Prettier
echo 'Running Prettier...'
npm run format

# Lint
echo 'Running Lint...'
npm run lint

# Unit Tests
echo 'Running Unit tests...'
npm run test

# Remove os arquivos da pasta de coverage da área de staging
git reset HEAD coverage/